name: Create Release on New Version Tag

# This workflow is triggered on every push event to a tag.
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches tags like v1.0.0, v2.1.5, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Creates a new GitHub Release.
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          # This action automatically uses the tag that triggered the workflow.
          # The `files` parameter specifies which files to attach as assets.
          files: |
            theme.ts
            manifest.json
        env:
          # GITHUB_TOKEN is a secret token automatically provided by GitHub.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}