# The name of your workflow, which will be shown in the Actions tab of your repository.
name: Create Release

# This workflow is triggered when a new tag is pushed or when a release is created.
# The 'release' event is fired when a release is published or updated in the UI.
# The 'push: tags' event is fired when you push a new tag from your local machine.
on:
  release:
    types: [created, published]
  push:
    tags:
      - 'v*' # This pattern matches any tag that starts with 'v', like v1.0.0.

# A single job to handle the creation of the release and uploading of assets.
jobs:
  build-and-release:
    # The runner environment where the job will execute. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # A list of steps to be executed within this job.
    steps:
      # Step 1: Check out the repository's code so the workflow can access your files.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Create a new GitHub Release and attach the specified files.
      # The 'softprops/action-gh-release' is a convenient community-supported action for this purpose.
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # The files property specifies which files to include as release assets.
          # You can specify multiple files by separating them with a space.
          # Here, we are including the two files requested by the user.
          files: |
            theme.css
            manifest.json
          # The 'name' property is used to set the title of the release.
          # We use the 'github.ref_name' context variable to get the tag name (e.g., 'v1.0.0').
          name: "Release ${{ github.ref_name }}"
